---
name: "Finseer"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Make requests to jellyseer from jellyfin"
description: >
  Make requests to jellyseer from jellyfin
category: "General"
owner: "RA341"
artifacts:
- "Finseer.dll"
changelog: >
  changelog
